# Generated by Django 3.2.16 on 2023-02-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], default='unknown', max_length=32),
        ),
    ]
