# Generated by Django 3.2.16 on 2023-02-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('unknown', 'unknown'), ('female', 'female'), ('male', 'male')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_vehicle_info',
            field=models.CharField(blank=True, default='None', max_length=256, null=True),
        ),
    ]
