# Generated by Django 3.2.16 on 2023-02-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230131_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('unknown', 'unknown'), ('male', 'male'), ('female', 'female')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('Sports Car', 'Sports Car'), ('SUV', 'SUV'), ('Sedan', 'Sedan')], default='Sedan', max_length=256),
        ),
    ]
