# Generated by Django 3.2.16 on 2023-02-01 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230201_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default='unknown', max_length=32),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=256)),
                ('arrival_time', models.DateTimeField()),
                ('passenger_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed')], default='open', max_length=32)),
                ('special_request', models.CharField(blank=True, default='', max_length=256)),
                ('special_vehicle_type', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='user.user')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user.user')),
                ('sharer', models.ManyToManyField(blank=True, related_name='sharer', to='user.User')),
            ],
        ),
    ]
