# Generated by Django 3.2.16 on 2023-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('unknown', 'unknown'), ('female', 'female'), ('male', 'male')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sports Car', 'Sports Car')], default='Sedan', max_length=256),
        ),
    ]
