# Generated by Django 3.2.16 on 2023-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('unknown', 'unknown'), ('male', 'male')], default='unknown', max_length=32),
        ),
    ]
