# Generated by Django 3.2.16 on 2023-02-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('unknown', 'unknown'), ('male', 'male')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('SUV', 'SUV')], default='Sedan', max_length=256),
        ),
    ]
