# Generated by Django 3.2.16 on 2023-02-05 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='passenger_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_request',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_vehicle_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_passenger',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('unknown', 'unknown'), ('male', 'male')], default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_vehicle_info',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('Sports Car', 'Sports Car'), ('SUV', 'SUV'), ('Sedan', 'Sedan')], default='Sedan', max_length=64),
        ),
    ]
