# Generated by Django 3.2.16 on 2023-02-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20230205_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unknown', 'unknown')], default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('Sports Car', 'Sports Car'), ('SUV', 'SUV'), ('Sedan', 'Sedan')], default='Sedan', max_length=64),
        ),
    ]
