# Generated by Django 4.1.6 on 2023-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_sex_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('unknown', 'unknown'), ('female', 'female')], default='unknown', max_length=64),
        ),
    ]
