# Generated by Django 4.1.6 on 2023-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unknown', 'unknown')], default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(choices=[('Sports Car', 'Sports Car'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], default='Sedan', max_length=64),
        ),
    ]
