# Generated by Django 4.1.6 on 2023-02-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_user_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('unknown', 'unknown'), ('female', 'female'), ('male', 'male')], default='unknown', max_length=64),
        ),
    ]
